# Prometheus Configuration for SmartMarketOOPS
# Monitors all system components with trading-specific metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smartmarket-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
# The rules should be placed in the rules directory
rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Trading System
  - job_name: 'ml-system'
    static_configs:
      - targets: ['ml-system:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # Analysis-Execution Bridge
  - job_name: 'bridge'
    static_configs:
      - targets: ['bridge:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s  # More frequent for real-time trading
    scrape_timeout: 3s

  # Frontend Application
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Database Monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # System Monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Trading-Specific Monitoring
  - job_name: 'trading-metrics'
    static_configs:
      - targets: ['ml-system:8000', 'bridge:8000']
    metrics_path: '/trading/metrics'
    scrape_interval: 5s  # High frequency for trading metrics
    params:
      module: ['trading']

  # Delta Exchange API Monitoring
  - job_name: 'delta-exchange-health'
    static_configs:
      - targets: ['bridge:8000']
    metrics_path: '/external/delta/health'
    scrape_interval: 30s

  # WebSocket Connection Monitoring
  - job_name: 'websocket-metrics'
    static_configs:
      - targets: ['bridge:8000']
    metrics_path: '/ws/metrics'
    scrape_interval: 10s

  # ML Model Performance
  - job_name: 'ml-model-metrics'
    static_configs:
      - targets: ['ml-system:8000']
    metrics_path: '/ml/metrics'
    scrape_interval: 60s  # Model metrics don't change as frequently

  # Risk Management Metrics
  - job_name: 'risk-metrics'
    static_configs:
      - targets: ['bridge:8000']
    metrics_path: '/risk/metrics'
    scrape_interval: 10s

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.smartmarket.com/api/v1/write"
    basic_auth:
      username: "smartmarket"
      password_file: "/etc/prometheus/remote_write_password"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
